### ISSUE TITLE
Demo project ?

### ISSUE THREAD

**Issue by vlordier** [synw/django-rechat#2]
To show how things (instant / presence / rechat) can work together and what they do, a demo project would be welcome.

**Comment by synw** [comment]
Yes it always good to have a demo. I may do a demo app. For now I have a script that installs the whole thing: https://github.com/synw/django-mogo (not documented properly actually but it works). Clone that and run it with the real time flag: 

`python djangomogo -rt`

You will get instant and presence installed together, rechat is not packed in because it needs more work. But this script installs a whole bunch of stuff that people do not need for such a demo, so yes I should make a demo project for those real time modules.
[ Edit ] The django-mogo script whith the -rt flag also installs this: https://github.com/synw/django-mqueue-livefeed

**Comment by synw** [comment]
I have made an installer and demo for Django Instant: https://github.com/synw/django-instant-installer

Its a bash script that takes care of all the boring install and configuration work. It does everything: just run it and open your browser. This is supposed to provide an easy way to try and install the stuff.

Please let me know if it works well if you give it a try.

[ Edit ] : This installs the following Instant modules: [django-presence](https://github.com/synw/django-presence) and  [django-mqueue-livefeed](https://github.com/synw/django-mqueue-livefeed). I might add  Rechat and [django-hitsfeed](https://github.com/synw/django-hitsfeed) later when they will be more usable: these last two were initialy proof of concept/test apps.

**Comment by synw** [comment]
This package has been refactored for django-instant 2 and now provides some Alpinejs templates and a frontend. It has been published on pip. And finally after all these years there is an example project: https://github.com/synw/django-rechat-example
